<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySite($sitename){
        $qb = $this->createQueryBuilder("a")
                ->select("a, s")
                ->leftJoin("a.site", "s")
                ->where("s.slug = :slug")
                ->setParameter("slug", $sitename)
                ->orderBy("a.date", "DESC");
        
        return $qb->getQuery()->getResult();
    }
}
