<?php

namespace AppBundle\Repository;

/**
 * ImageSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
