<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Site;

/**
 * SectionSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionSiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySectionAndSite($slug, Site $site){
        $qb = $this->createQueryBuilder("ss")
                ->select('ss')
                ->leftJoin("ss.site", "s")
                ->leftJoin("ss.section", "se")
                ->where("s.id = :site")
                ->andWhere("se.slug = :slug")
                ->setParameter("site", $site->getId())
                ->setParameter('slug', $slug);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
