<?php

namespace AppBundle\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug($slug){
        $qb = $this->createQueryBuilder("s")
                ->select("s, u, ss, se, a, c, i")
                ->leftJoin("s.users", "u")
                ->leftJoin("s.sectionsSite", "ss")
                ->leftJoin("ss.section", "se")
                ->leftJoin("s.articles", "a")
                ->leftJoin("s.contacts", "c")
                ->leftJoin("s.pictures", "i")
                ->where('s.slug = :slug')
                ->addOrderBy("ss.ordering", 'ASC')
                ->addOrderBy("i.date", 'DESC')
                ->addOrderBy("a.date", 'DESC')
                ->setParameter("slug", $slug);
        
        return $qb->getQuery()->getOneOrNullResult();
    }
}
